"""initial

Revision ID: 07cfca043074
Revises: 
Create Date: 2026-03-19 22:00:37.058085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07cfca043074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_phone'), 'otps', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'premium', name='subscriptiontier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('senior_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='conversationrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_session_id'), 'ai_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=512), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('screenshot', 'audio', 'video', 'document', name='filetype'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_user_id'), 'evidence', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('member_user_id', sa.UUID(), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('can_view_alerts', sa.Boolean(), nullable=False),
    sa.Column('can_trigger_panic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('link_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('threat_category', sa.String(length=100), nullable=True),
    sa.Column('scan_provider', sa.String(length=100), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_scans_user_id'), 'link_scans', ['user_id'], unique=False)
    op.create_table('otp_vault_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('raw_otp', sa.String(length=20), nullable=True),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('source_app', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_vault_entries_user_id'), 'otp_vault_entries', ['user_id'], unique=False)
    op.create_table('scam_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('detection_reason', sa.Text(), nullable=True),
    sa.Column('audio_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scam_calls_user_id'), 'scam_calls', ['user_id'], unique=False)
    op.create_table('security_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('threats_detected', sa.Integer(), nullable=False),
    sa.Column('apps_scanned', sa.Integer(), nullable=False),
    sa.Column('links_scanned', sa.Integer(), nullable=False),
    sa.Column('calls_analyzed', sa.Integer(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('top_threats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_reports_user_id'), 'security_reports', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('app_risk', 'otp_fraud', 'phishing', 'scam_call', 'remote_access', 'wifi_unsafe', 'data_leak', 'banking', 'panic', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alertseverity'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('app_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('safe', 'low', 'medium', 'high', 'critical', name='risklevel'), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system_app', sa.Boolean(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('threat_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_scans_device_id'), 'app_scans', ['device_id'], unique=False)
    op.create_table('network_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('app_package', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('bytes_received', sa.BigInteger(), nullable=False),
    sa.Column('destination_ip', sa.String(length=50), nullable=True),
    sa.Column('destination_domain', sa.String(length=255), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_activities_device_id'), 'network_activities', ['device_id'], unique=False)
    op.create_table('wifi_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('ssid', sa.String(length=255), nullable=True),
    sa.Column('bssid', sa.String(length=50), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('encryption_type', sa.String(length=50), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('risk_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wifi_scans_device_id'), 'wifi_scans', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wifi_scans_device_id'), table_name='wifi_scans')
    op.drop_table('wifi_scans')
    op.drop_index(op.f('ix_network_activities_device_id'), table_name='network_activities')
    op.drop_table('network_activities')
    op.drop_index(op.f('ix_app_scans_device_id'), table_name='app_scans')
    op.drop_table('app_scans')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_security_reports_user_id'), table_name='security_reports')
    op.drop_table('security_reports')
    op.drop_index(op.f('ix_scam_calls_user_id'), table_name='scam_calls')
    op.drop_table('scam_calls')
    op.drop_index(op.f('ix_otp_vault_entries_user_id'), table_name='otp_vault_entries')
    op.drop_table('otp_vault_entries')
    op.drop_index(op.f('ix_link_scans_user_id'), table_name='link_scans')
    op.drop_table('link_scans')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_evidence_user_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_session_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otps_phone'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
