"""add_error_logs_table

Revision ID: 3bf328167739
Revises: 07cfca043074
Create Date: 2026-03-19 23:40:40.397971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf328167739'
down_revision: Union[str, None] = '07cfca043074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('exception_type', sa.String(length=255), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_level'), 'error_logs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_logs_level'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
