"""add_address_profile_fields

Revision ID: 519e8e8aa0ae
Revises: 6098a82b5e06
Create Date: 2026-03-20 13:11:17.510820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519e8e8aa0ae'
down_revision: Union[str, None] = '6098a82b5e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('alt_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('flat_no', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('building', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('pin_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_code')
    op.drop_column('users', 'country')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street')
    op.drop_column('users', 'building')
    op.drop_column('users', 'flat_no')
    op.drop_column('users', 'alt_phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
