"""phone_email_otp_support

Revision ID: 6098a82b5e06
Revises: 3bf328167739
Create Date: 2026-03-20 00:07:22.501113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6098a82b5e06'
down_revision: Union[str, None] = '3bf328167739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('otps', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.alter_column('otps', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('otps', 'email')
    # ### end Alembic commands ###
