"""add emergency_contacts

Revision ID: d845ea331d7d
Revises: e9e22b86f70c
Create Date: 2026-04-04 21:33:19.726441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd845ea331d7d'
down_revision: Union[str, None] = 'e9e22b86f70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_behavior_events_occurred_at', table_name='behavior_events')
    op.drop_index('idx_behavior_events_user_id', table_name='behavior_events')
    op.drop_table('behavior_events')
    op.drop_index('idx_community_scam_city', table_name='community_scam_reports')
    op.drop_index('idx_community_scam_created_at', table_name='community_scam_reports')
    op.drop_index('idx_community_scam_pincode', table_name='community_scam_reports')
    op.drop_index('idx_community_scam_user_id', table_name='community_scam_reports')
    op.drop_table('community_scam_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_scam_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scam_type', postgresql.ENUM('phishing_link', 'fake_job', 'lottery_fraud', 'investment_scam', 'bank_fraud', 'otp_fraud', 'romance_scam', 'tech_support_scam', 'parcel_scam', 'other', name='scamtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('upvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='community_scam_reports_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='community_scam_reports_pkey')
    )
    op.create_index('idx_community_scam_user_id', 'community_scam_reports', ['user_id'], unique=False)
    op.create_index('idx_community_scam_pincode', 'community_scam_reports', ['pincode'], unique=False)
    op.create_index('idx_community_scam_created_at', 'community_scam_reports', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_community_scam_city', 'community_scam_reports', ['city'], unique=False)
    op.create_table('behavior_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('clicked_unknown_link', 'installed_suspicious_app', 'shared_otp', 'connected_open_wifi', 'received_scam_call', 'submitted_form_on_suspicious_site', 'opened_scam_message', 'granted_excessive_permissions', 'disabled_security_feature', name='behavioreventtype'), autoincrement=False, nullable=False),
    sa.Column('risk_contribution', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='behavior_events_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='behavior_events_pkey')
    )
    op.create_index('idx_behavior_events_user_id', 'behavior_events', ['user_id'], unique=False)
    op.create_index('idx_behavior_events_occurred_at', 'behavior_events', [sa.text('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###
