"""add_community_scam_behavior_event

Revision ID: e9e22b86f70c
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 20:35:05.527466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e22b86f70c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('is_child_profile', sa.Boolean(), nullable=False))
    op.add_column('family_members', sa.Column('content_filter_enabled', sa.Boolean(), nullable=False))
    op.add_column('family_members', sa.Column('cyberbullying_alerts', sa.Boolean(), nullable=False))
    op.drop_constraint('recordings_share_token_key', 'recordings', type_='unique')
    op.drop_index('ix_recordings_share_token', table_name='recordings')
    op.create_index(op.f('ix_recordings_share_token'), 'recordings', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_share_token'), table_name='recordings')
    op.create_index('ix_recordings_share_token', 'recordings', ['share_token'], unique=False)
    op.create_unique_constraint('recordings_share_token_key', 'recordings', ['share_token'])
    op.drop_column('family_members', 'cyberbullying_alerts')
    op.drop_column('family_members', 'content_filter_enabled')
    op.drop_column('family_members', 'is_child_profile')
    # ### end Alembic commands ###
